swagger: "2.0"
info:
  version: "0.0.1"
  title: PG Search App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /searchEmail:
    # binds a127 app logic to a route
    x-swagger-router-controller: pg_search
    get:
      description: Searches PG database table for email presented, if successful, inserts that contact row into Salesforce database and returns the confirmation, a 15/18 digit Salesforce ID.
      # used as method name of the controller
      operationId: searchEmail
      parameters: 
        - name: emailAddy
          in: query
          description: The email provided to search
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /searchPhoneNumber:
    # binds a127 app logic to a route
    x-swagger-router-controller: pg_search
    get:
      description: Searches PG database table for phone number presented, if successful, inserts that contact row into Salesforce database and returns the confirmation, a 15/18 digit Salesforce ID.
      # used as the method name of the controller
      operationId: searchPhone
      parameters:
        - name: phoneNum
          in: query
          description: The phone number provided to search
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
